# Generated by Django 3.1.3 on 2020-11-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Link',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
