# Generated by Django 3.1.3 on 2020-11-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201129_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Link',
            field=models.URLField(),
        ),
    ]
