# Generated by Django 3.1.3 on 2020-11-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201130_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='model',
            new_name='Model',
        ),
    ]
