# Generated by Django 3.1.3 on 2020-12-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201202_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='txplnation',
            new_name='explnation',
        ),
    ]
