# Generated by Django 3.1.3 on 2020-12-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201202_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
        ),
    ]
