# Generated by Django 3.1.3 on 2020-12-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidder',
            field=models.CharField(default=32, max_length=64),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing_id',
            field=models.IntegerField(default=32, max_length=64),
        ),
    ]
