

# Generated by Django 3.1.3 on 2020-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201204_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(default=64, max_length=32),
        ),
    ]
