# Generated by Django 3.1.3 on 2020-12-04 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20201204_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
