# Generated by Django 3.1.3 on 2020-12-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20201205_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.IntegerField(),
        ),
    ]
