# Generated by Django 3.1.3 on 2020-12-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20201205_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='model',
        ),
    ]
