# Generated by Django 3.1.3 on 2020-12-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_remove_listing_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.CharField(default='', max_length=64),
        ),
    ]
