# Generated by Django 3.1.3 on 2020-12-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_listing_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidder',
            field=models.CharField(default='', max_length=64),
        ),
    ]
