# Generated by Django 3.1.3 on 2020-12-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20201206_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='model',
        ),
    ]
