# Generated by Django 3.1.3 on 2020-12-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20201206_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Category',
            new_name='Categoryy',
        ),
    ]
