# Generated by Django 3.1.3 on 2020-12-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20201206_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Categoryy',
            new_name='Categories',
        ),
    ]
