# Generated by Django 3.1.3 on 2020-12-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20201206_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Categories',
            new_name='Category',
        ),
    ]
