# Generated by Django 3.1.3 on 2020-12-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20201206_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=64)),
                ('bid_winner', models.CharField(max_length=64)),
                ('li_id', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('title', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
