# Generated by Django 3.1.3 on 2020-12-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_auto_20201206_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidder',
            field=models.CharField(blank='', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='close',
            field=models.BooleanField(default=True),
        ),
    ]
