# Generated by Django 3.1.3 on 2020-12-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20201207_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
