# Generated by Django 3.1.3 on 2020-12-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_auto_20201207_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
