# Generated by Django 3.1.3 on 2020-12-08 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
from decimal import Decimal



class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_auto_20201207_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=64)),
                ('winner', models.CharField(max_length=64)),
                ('listingid', models.IntegerField()),
                ('winprice', models.IntegerField()),
                ('title', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pro_winner',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='list_id',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='title',
        ),
        migrations.AddField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 12, 26, 39, 517756, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='bid',
            name='listingid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='value_offer',
            field=models.DecimalField(decimal_places=2, default=Decimal(0), max_digits=8),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.FloatField(),
        ),
    ]
