# Generated by Django 3.1.3 on 2020-12-08 12:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_auto_20201208_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 12, 28, 57, 364625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
