# Generated by Django 3.1.3 on 2020-12-08 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_auto_20201208_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 12, 32, 18, 428882, tzinfo=utc)),
        ),
    ]
