# Generated by Django 3.1.3 on 2020-12-08 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_auto_20201208_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='value_offer',
        ),
        migrations.AddField(
            model_name='bid',
            name='close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 14, 27, 41, 104413, tzinfo=utc)),
        ),
    ]
