# Generated by Django 3.1.3 on 2020-12-08 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_auto_20201208_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 14, 29, 54, 296429, tzinfo=utc)),
        ),
    ]
