# Generated by Django 3.1.3 on 2020-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0052_listing_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
