# Generated by Django 3.1.3 on 2020-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0053_auto_20201208_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidder',
            field=models.IntegerField(),
        ),
    ]
