# Generated by Django 3.1.3 on 2020-12-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0055_remove_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidder',
            field=models.CharField(max_length=64),
        ),
    ]
