# Generated by Django 3.1.3 on 2020-12-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0056_auto_20201209_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='highest_bid',
            field=models.FloatField(default=0.0),
        ),
    ]
