# Generated by Django 3.1.3 on 2020-12-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0057_bid_highest_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='highest_bid',
        ),
    ]
