# Generated by Django 3.1.3 on 2020-12-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0060_listing_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(default=models.IntegerField()),
        ),
    ]
