# Generated by Django 3.1.3 on 2020-12-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0061_auto_20201209_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(),
        ),
    ]
