# Generated by Django 3.1.3 on 2020-12-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0064_auto_20201209_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(default=models.IntegerField()),
        ),
    ]
