# Generated by Django 3.1.3 on 2020-12-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0066_auto_20201212_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(null=True),
        ),
    ]
