# Generated by Django 3.1.3 on 2020-12-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0067_auto_20201214_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(default=models.IntegerField(), null=True),
        ),
    ]
