# Generated by Django 3.1.3 on 2020-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0068_auto_20201215_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
