# Generated by Django 3.1.3 on 2020-12-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0069_auto_20201215_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(default=models.IntegerField(verbose_name=models.IntegerField()), null=True),
        ),
    ]
