# Generated by Django 3.1.3 on 2020-12-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0073_remove_listing_high'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='auctions.category'),
        ),
    ]
