# Generated by Django 3.1.3 on 2020-12-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0083_auto_20201218_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bidder',
        ),
    ]
