# Generated by Django 3.1.3 on 2020-12-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0084_remove_listing_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidder',
            field=models.CharField(default=UserWarning, max_length=64),
        ),
    ]
