# Generated by Django 3.1.3 on 2020-12-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0086_auto_20201218_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidder',
            field=models.CharField(default='holder', max_length=64),
        ),
    ]
