# Generated by Django 3.1.3 on 2020-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0087_auto_20201218_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidder',
            field=models.CharField(default='No one', max_length=64),
        ),
    ]
