# Generated by Django 3.1.3 on 2020-12-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0089_auto_20201218_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidder',
            field=models.CharField(max_length=64),
        ),
    ]
