# Generated by Django 3.1.3 on 2020-12-18 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0090_auto_20201218_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidder',
            field=models.CharField(default="Holder", max_length=64),
            preserve_default=False,
        ),
    ]
