# Generated by Django 3.1.3 on 2020-12-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0091_auto_20201218_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidder',
            field=models.IntegerField(),
        ),
    ]
