# Generated by Django 3.1.3 on 2020-12-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0092_auto_20201220_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidder',
            field=models.CharField(max_length=64),
        ),
    ]
