# Generated by Django 3.1.3 on 2020-12-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0094_auto_20201220_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
