# Generated by Django 3.1.3 on 2021-02-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0095_category_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.CharField(default='', max_length=64),
        ),
    ]
