# Generated by Django 3.1.3 on 2021-02-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0096_auto_20210216_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work',
        ),
    ]
