# Generated by Django 3.1.3 on 2021-02-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0097_remove_user_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidder',
            field=models.CharField(default='No one!', max_length=64, null=True),
        ),
    ]
